<?php
/**
 * Range formatter accepts a positive integer range and generates a formatted output
 * 
 * @author shanosh
 */
class RangeFormatter{
	
	/**
	 * Stores the range generated by start and end values
	 * 
	 * @var Array
	 */
	protected $range;
	
	/**
	 * Stores the multipliers and its lables
	 * 
	 * @var Array
	 */
	protected $keywords = array(3 => 'Fizz', 5 => 'Buzz');
	
	/**
	 * Stores the generated formatted output
	 * 
	 * @var String
	 */
	public $output;
	
	/**
	 * 
	 * 
	 * @var Array
	 */
	public $outputRange;
	
	/**
	 * The constructor accepts a positive integer range.
	 * It will throw out an exception if else
	 *
	 * @param Int $start starting number of the range
	 * @param Int $end ending number of the range
	 */
	public function __construct($start, $end){	
		
		//check if both numbers are positive integers and that end number is greater
		if(!is_int($start) 
			|| !is_int($end)
			|| $start < 0
			|| $end < 0
			|| $start > $end
		){
			throw new Exception("Invalid parameters");	
		}
	
	
		//set start and end properties
		$this->range = range($start, $end);

	
	}
		
	
	/**
	 * Generates the formatted output based on the range
	 * 
	 * @return String generated string
	 */
	public function generateOutput(){
		
		//if the range is not set just return an empty string
		if(empty($this->range)){
			return $this->output = '';
		}
		
		/**
		 * used to keep an incremental track of consecutive Fizzes/Buzzes
		 * Once there is a consecutive Fizz and a Buzz this increments up to 2 and a Bazz is displayed
		 * instead of the integer and the value of this becomes 0 again
		 */
		$bazzStatus = 0;
		
		//return generated output
		foreach ($this->range as $n){
			$printInt = true;
				
			foreach($this->keywords as $multiplier => $label){
				if($n % $multiplier == 0){
					$this->output .= $label;
					$printInt = false;
					
					//if it is a fizz or a buzz increment the bazzStatus by 1
					if($multiplier == 3 || $multiplier = 5){
						$bazzStatus++;
					}
				}
			}
			
			//if bazzStatus has reached stage 2 we display 'Bazz' or else the integer	
			if($printInt && $bazzStatus == 2){
				$this->output .= 'Bazz';
				$bazzStatus = 0;
			}else if($printInt){
				$this->output .= $n;
				$bazzStatus = 0;
			}
			
			
			$this->output .= ' ';
		}
		
		return trim($this->output);
		
	}
	
	/**
	 * Prints the output
	 * 
	 * @return void
	 */
	public function display(){		
		
		echo $this->output;
	}
	
	
}

$rangeFormatter = new RangeFormatter(4,11);
$rangeFormatter->generateOutput();
$rangeFormatter->display();